import {
    AuthorizationError,
    NotFoundError,
    ParameterError,
    RequestMethod,
} from '@lightdash/common';
import { LightdashAnalytics } from '../analytics/LightdashAnalytics';
import { LightdashConfig } from '../config/parseConfig';
import { PersonalAccessTokenModel } from '../models/DashboardModel/PersonalAccessTokenModel';
import { UserModel } from '../models/UserModel';
import { BaseService } from './BaseService';

export type McpTokenExchangeResult = {
    accessToken: string;
    tokenType: 'ApiKey';
    expiresAt: string;
    userUuid: string;
    email: string;
};

type McpTokenExchangeServiceArguments = {
    lightdashConfig: LightdashConfig;
    analytics: LightdashAnalytics;
    userModel: UserModel;
    personalAccessTokenModel: PersonalAccessTokenModel;
};

/**
 * Service-to-service: MCP verifies a shared secret, then mints a short-lived
 * PAT for an existing Lightdash user identified by email (from Keycloak JWT).
 *
 * Authorization: caller must present LIGHTDASH_MCP_TOKEN_EXCHANGE_SECRET.
 * No end-user session / CASL create-PAT check — minting is a trusted MCP op.
 * The issued PAT still carries the target user's normal API permissions.
 */
export class McpTokenExchangeService extends BaseService {
    private readonly lightdashConfig: LightdashConfig;

    private readonly analytics: LightdashAnalytics;

    private readonly userModel: UserModel;

    private readonly personalAccessTokenModel: PersonalAccessTokenModel;

    constructor(args: McpTokenExchangeServiceArguments) {
        super();
        this.lightdashConfig = args.lightdashConfig;
        this.analytics = args.analytics;
        this.userModel = args.userModel;
        this.personalAccessTokenModel = args.personalAccessTokenModel;
    }

    private assertExchangeSecret(authorizationHeader: string | undefined): void {
        const configured =
            this.lightdashConfig.mcp.tokenExchangeSecret?.trim();
        if (!configured) {
            throw new AuthorizationError(
                'MCP token exchange is not configured (LIGHTDASH_MCP_TOKEN_EXCHANGE_SECRET)',
            );
        }
        if (!authorizationHeader) {
            throw new AuthorizationError(
                'Missing Authorization Bearer token for MCP token exchange',
            );
        }
        const match = authorizationHeader.match(/^Bearer\s+(.+)$/i);
        const presented = match?.[1]?.trim();
        if (!presented || presented !== configured) {
            throw new AuthorizationError(
                'Invalid MCP token exchange secret',
            );
        }
    }

    resolveTtlSeconds(): number {
        const { patTtlSeconds, patTtlMaxSeconds } = this.lightdashConfig.mcp;
        return Math.min(patTtlSeconds, patTtlMaxSeconds);
    }

    async exchangeEmailForPat(options: {
        authorizationHeader: string | undefined;
        email: string;
    }): Promise<McpTokenExchangeResult> {
        this.assertExchangeSecret(options.authorizationHeader);

        const email = options.email?.trim();
        if (!email || !email.includes('@')) {
            throw new ParameterError('email is required');
        }

        const user =
            await this.userModel.findSessionUserByPrimaryEmail(email);
        if (!user) {
            throw new NotFoundError(
                `No Lightdash user with primary email: ${email}`,
            );
        }

        const ttlSeconds = this.resolveTtlSeconds();
        const expiresAt = new Date(Date.now() + ttlSeconds * 1000);

        const created = await this.personalAccessTokenModel.create(user, {
            description: 'mcp-keycloak-exchange',
            expiresAt,
            autoGenerated: true,
        });

        this.analytics.track({
            userId: user.userUuid,
            event: 'personal_access_token.created',
            properties: {
                userId: user.userUuid,
                autoGenerated: true,
                method: RequestMethod.BACKEND,
            },
        });

        return {
            accessToken: created.token,
            tokenType: 'ApiKey',
            expiresAt: expiresAt.toISOString(),
            userUuid: user.userUuid,
            email,
        };
    }
}
