import { formatTimestamp } from '@lightdash/common';
import {
    ActionIcon,
    Alert,
    Button,
    CopyButton,
    Modal,
    Select,
    Stack,
    TextInput,
    Title,
    Tooltip,
} from '@mantine/core';
import { useForm } from '@mantine/form';
import { IconAlertCircle, IconCheck, IconCopy } from '@tabler/icons-react';
import { type FC } from 'react';
import { useTranslation } from 'react-i18next';

import useHealth from '../../../hooks/health/useHealth';
import { useCreateAccessToken } from '../../../hooks/useAccessToken';
import MantineIcon from '../../common/MantineIcon';
import { useExpireOptions } from './useExpireOptions';

export const CreateTokenModal: FC<{
    onBackClick: () => void;
}> = ({ onBackClick }) => {
    const { t } = useTranslation();
    const health = useHealth();

    const {
        data,
        mutate: createAccessToken,
        isLoading,
        isSuccess,
    } = useCreateAccessToken();

    const expireOptions = useExpireOptions(true);

    const form = useForm({
        initialValues: {
            description: '',
            expiresAt: expireOptions[0].value,
        },
    });

    const handleOnSubmit = form.onSubmit(({ description, expiresAt }) => {
        const currentDate = new Date();
        const dateWhenExpires = !!Number(expiresAt)
            ? new Date(
                  currentDate.setDate(
                      currentDate.getDate() + Number(expiresAt),
                  ),
              )
            : undefined;

        createAccessToken({
            description,
            expiresAt: dateWhenExpires ?? null,
            autoGenerated: false,
        });
    });

    return (
        <Modal
            size="lg"
            opened
            onClose={() => {
                onBackClick();
            }}
            title={
                <Title order={4}>
                    {data
                        ? t(
                              'components_user_settings_access_tokens_panel_create_token.title.has_been_generated',
                          )
                        : t(
                              'components_user_settings_access_tokens_panel_create_token.title.new_token',
                          )}
                </Title>
            }
        >
            {!isSuccess ? (
                <form onSubmit={handleOnSubmit}>
                    <Stack spacing="md">
                        <TextInput
                            label={t(
                                'components_user_settings_access_tokens_panel_create_token.form.token_for.label',
                            )}
                            disabled={isLoading}
                            placeholder={t(
                                'components_user_settings_access_tokens_panel_create_token.form.token_for.placeholder',
                            )}
                            required
                            {...form.getInputProps('description')}
                        />

                        <Select
                            withinPortal
                            defaultValue={expireOptions[0].value}
                            label={t(
                                'components_user_settings_access_tokens_panel_create_token.form.expiration.label',
                            )}
                            data={expireOptions}
                            required
                            disabled={isLoading}
                            {...form.getInputProps('expiresAt')}
                        ></Select>

                        <Button type="submit" ml="auto" loading={isLoading}>
                            {t(
                                'components_user_settings_access_tokens_panel_create_token.form.generate_token',
                            )}
                        </Button>
                    </Stack>
                </form>
            ) : (
                <Stack spacing="md">
                    <TextInput
                        id="invite-link-input"
                        label={t(
                            'components_user_settings_access_tokens_panel_create_token.form.token.label',
                        )}
                        readOnly
                        className="sentry-block ph-no-capture"
                        value={data.token}
                        rightSection={
                            <CopyButton value={data.token}>
                                {({ copied, copy }) => (
                                    <Tooltip
                                        label={
                                            copied
                                                ? t(
                                                      'components_user_settings_access_tokens_panel_create_token.form.copied',
                                                  )
                                                : t(
                                                      'components_user_settings_access_tokens_panel_create_token.form.copy',
                                                  )
                                        }
                                        withArrow
                                        position="right"
                                    >
                                        <ActionIcon
                                            color={copied ? 'teal' : 'gray'}
                                            onClick={copy}
                                        >
                                            <MantineIcon
                                                icon={
                                                    copied
                                                        ? IconCheck
                                                        : IconCopy
                                                }
                                            />
                                        </ActionIcon>
                                    </Tooltip>
                                )}
                            </CopyButton>
                        }
                    />
                    <TextInput
                        id="invite-link-input"
                        label={t(
                            'components_user_settings_access_tokens_panel_create_token.form.authentication.label',
                        )}
                        className="sentry-block ph-no-capture"
                        readOnly
                        value={`lightdash login ${health.data?.siteUrl} --token ${data.token}`}
                        rightSection={
                            <CopyButton
                                value={t(
                                    'components_user_settings_access_tokens_panel_create_token.form.authentication.value',
                                    {
                                        siteUrl: health.data?.siteUrl,
                                        token: data.token,
                                    },
                                )}
                            >
                                {({ copied, copy }) => (
                                    <Tooltip
                                        label={
                                            copied
                                                ? t(
                                                      'components_user_settings_access_tokens_panel_create_token.form.copied',
                                                  )
                                                : t(
                                                      'components_user_settings_access_tokens_panel_create_token.form.copy',
                                                  )
                                        }
                                        withArrow
                                        position="right"
                                    >
                                        <ActionIcon
                                            color={copied ? 'teal' : 'gray'}
                                            onClick={copy}
                                        >
                                            <MantineIcon
                                                icon={
                                                    copied
                                                        ? IconCheck
                                                        : IconCopy
                                                }
                                            />
                                        </ActionIcon>
                                    </Tooltip>
                                )}
                            </CopyButton>
                        }
                    />
                    <Alert icon={<MantineIcon icon={IconAlertCircle} />}>
                        {data.expiresAt &&
                            `${t(
                                'components_user_settings_access_tokens_panel_create_token.alert.part_1',
                            )}
                        ${formatTimestamp(data.expiresAt)} `}
                        {t(
                            'components_user_settings_access_tokens_panel_create_token.alert.part_2',
                        )}
                    </Alert>
                </Stack>
            )}
        </Modal>
    );
};
